Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you
might choose one over the other.

In [ ]:
Ans: The difference between ordinal encoding and label encoding are :
    ordinal encoding is used when the categorical data has an inherent order or hierarachy, such as low, medium,
    and high or small, medium and large.
    
    Similarly,  Label encoding is used when the categorical data has no inherent order or hierarchy, such as colors
    or names. In label encoding, each category is assigned a unique numerical value, with no particular ordering.
    
    For example, if we are encoding a dataset that contains a categorical variable "education level" with 
    categories "high school", "some college", "bachelor's degree", "master's degree", and "doctorate degree",
    we might choose to use Ordinal Encoding, as the categories have an inherent order based on the level of 
    education attained.

On the other hand, if we are encoding a dataset that contains a categorical variable "color" with categories
"red", "blue", and "green", we might choose to use Label Encoding, as there is no inherent order to the 
categories.

In [ ]:
Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in
a machine learning project.

In [ ]:
Ans: Target Guided Encoding can be especially useful when working with categorical variables that have a strong
relationship with the target variables, as it can help to capture this relationship  in a more nuanced way than
other encoding techniques. It is important to note that target guided ordinal encoding may not be appropriate
in all cases, and it is always important to carefully evaluate the performance of different encoding techniques
 in the context of a specific machine learning project.
    
    

In [ ]:
Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

In [ ]:
Ans:- Covariance measures the direction and strength of the linear relationship between two variables.
it is important in statiscal analysis because it helps to identify the strength and direction of the relation
ship between two variables.
It is important because it can be used to understand how changes in one variable affect changes in another
variable, and can also help in identifying relationships that can be used to make predication.

Covariance(X,Y) = [∑(Xi - X_mean)*(Yi - Y_mean)] / (n - 1)

In [ ]:
Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium,
large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library.
Show your code and explain the output.

In [2]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
data = pd.DataFrame({
      'color' : ['red', 'green', 'blue', 'gree','blue', 'red'],
    'Size' : ['small', 'medium', 'large', 'medium','small', 'large'],
    'Material' : ['wood', 'metal', 'plastic','metal', 'wood', 'plastic']
})

label = LabelEncoder()
data['color'] = label.fit_transform(data['color'])
data['Size'] = label.fit_transform(data['Size'])
data['Material'] = label.fit_transform(data['Material'])

print(data)

   color  Size  Material
0      3     2         2
1      2     1         0
2      0     0         1
3      1     1         0
4      0     2         2
5      3     0         1


In [ ]:
Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education
level. Interpret the results.

In [3]:
import numpy as np
import pandas as pd

data = pd.DataFrame({
'Age' : [30, 40, 50,60,70],
'Income' : [5000, 6000, 7000, 4500, 55000],
'Education Level' : [12, 16, 18, 10, 14]
})

cov_matrix = np.cov(data.T)
print(cov_matrix)

[[ 2.5000e+02  2.4625e+05 -5.0000e+00]
 [ 2.4625e+05  4.8850e+08  3.0000e+03]
 [-5.0000e+00  3.0000e+03  1.0000e+01]]


In [ ]:
Q6. You are working on a machine learning project with a dataset containing several categorical
variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD),
and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for
each variable, and why?

In [ ]:
Ans: for the 'Gender' variable, we can use label encoding since there are only two categories: Male and Female.
similarly, for the 'Eduacation Level' variable, we can use ordinal encoding since there is a natural ordering
to the categories.
and lastly, for the 'Employment Status' variable, we can use one-hot encoding since there is no natural ordering
to the categories and we want to avoid assigning any numerical values that mighty imply an ordering or magnitude.


In [ ]:
Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two
categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/
East/West). Calculate the covariance between each pair of variables and interpret the results.

In [4]:
import pandas as pd
import numpy as np

temperature = np.array([20, 25, 30, 35, 40])
humidity = np.array([50, 60, 40, 80, 90])
weather_condition = np.array(['Sunny', 'Sunny', 'Cloudy', 'Rainy', 'Rainy'])
wind_direction = np.array(['North', 'South', 'East', 'West', 'North'])

data = np.array([temperature, humidity]).T
cov_matrix = np.cov(data, rowvar = False)

print(cov_matrix)

[[ 62.5 125. ]
 [125.  430. ]]
